'use client';

import { useEffect, useRef} from 'react';
import * as THREE from 'three';
// @ts-ignore
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
// @ts-ignore
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';
import Head from 'next/head';

function ThreeScene() {
    const block3d = useRef(null)
    const height = window.innerWidth / 24 * 5

    useEffect(() => {


        const scene = new THREE.Scene();
        scene.background = new THREE.Color('#1a1a1a');

        const camera = new THREE.PerspectiveCamera(
            60,
            2,
            0.1,
            1000
        );
        camera.position.set(0, 2, 10);

        const renderer = new THREE.WebGLRenderer({ antialias: true });
        renderer.setPixelRatio(window.devicePixelRatio);
        renderer.setSize((window.innerWidth/12*5), (window.innerWidth/24*5));
        const mountNode = document.getElementById('three-container');
        if (mountNode) mountNode.appendChild(renderer.domElement);

        const controls = new OrbitControls(camera, renderer.domElement);
        controls.enableDamping = true;
        controls.dampingFactor = 0.04;
        controls.enableZoom = true;


        controls.minDistance = 9;
        controls.maxDistance = 11;
        controls.minPolarAngle = Math.PI / 2 - 0.108;
        controls.maxPolarAngle = Math.PI / 2 + 0.108;
        const light = new THREE.HemisphereLight("white", 'black');
        scene.add(light);

        const directionalLight = new THREE.DirectionalLight("white");
        directionalLight.position.set(1, 1, 1).normalize();
        scene.add(directionalLight);

        const loader = new GLTFLoader();
        loader.load(
            '/models/walter_white.glb',
            (gltf: any) => {
                const model = gltf.scene;
                model.scale.set(0.65, 0.65, 0.65);
                scene.add(model);

                const directionalLight1 = new THREE.DirectionalLight('white', 0.5);
                directionalLight1.position.set(5, 10, 5);
                directionalLight1.color.setHSL(0.6, 1, 0.9);
                scene.add(directionalLight1);

                const directionalLight2 = new THREE.DirectionalLight('white', 0.5);
                directionalLight2.position.set(-5, 10, -5);
                directionalLight2.color.setHSL(0.1, 1, 0.5);
                scene.add(directionalLight2);

                let hue1 = 15;
                let hue2 = 0.9;

                function animateGradient() {
                    hue1 += 0.005;
                    hue2 += 0.005;

                    if (hue1 > 1) hue1 -= 1;
                    if (hue2 > 1) hue2 -= 1;

                    directionalLight1.color.setHSL(hue1, 1, 0.5);
                    directionalLight2.color.setHSL(hue2, 1, 0.5);
                }

                function animateModel() {
                    model.rotation.y -= 0.0002;
                }

                function animate() {
                    requestAnimationFrame(animate);
                    animateModel();
                    animateGradient();
                    controls.update();
                    renderer.render(scene, camera);
                }

                animate();
            },
            undefined,
            (error: any) => {
                console.error('Ошибка загрузки модели:', error);
            }
        );

        const handleResize = () => {
            camera.aspect = 2
            camera.updateProjectionMatrix();
            renderer.setSize((window.innerWidth/12*5), (window.innerWidth/24*5));
        };

        window.addEventListener('resize', handleResize);

        return () => {
            window.removeEventListener('resize', handleResize);
            renderer.dispose();
        };
    }, []);

    return (
        <div className="w-full mb-2 p-4 bg-indigo-950 px-4 sm:px-6 py-10">
            <div className="max-w-7xl mx-auto flex flex-col-reverse lg:flex-row items-center gap-10">

                {/* Text Block */}
                <div className="w-full lg:w-1/2 text-white">
                    <h1 className="text-2xl sm:text-3xl font-extrabold mb-6 text-center lg:text-left leading-tight">
                        Welcome to my digital universe!
                    </h1>
                    <div className="bg-gradient-to-br from-neutral-900 to-indigo-800 p-6 rounded-2xl shadow-lg">
                        <p className="text-sm sm:text-base leading-relaxed text-justify text-neutral-100">
                            Here ideas are born and the most daring projects are realized. This is the place where code
                            meets creativity, and technologies become an instrument of art.
                            Come in, get inspired and find out how incredible worlds are created from lines of code...
                            In general — this text was generated by GPT.
                        </p>
                    </div>
                </div>

                {/* 3D Container */}
                <div
                    id="three-container"
                    ref={block3d}
                    className="w-auto h-auto rounded-3xl overflow-hidden shadow-xl bg-neutral-800"
                >
                    {/* Canvas вставляется внутрь по useRef */}
                </div>
            </div>
        </div>

    );
}

export default function Drag() {
    return (
        <>
            <Head>
                <title>3D Scene</title>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            </Head>
            <div className="flex flex-col items-center justify-center w-full h-auto bg-black">
                <ThreeScene/>
            </div>
        </>
    );
}
